import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
//<editor-fold defaultstate="collapsed" desc="comment">
import java.sql.Statement;
import java.sql.ResultSet;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * A2.java
 *
 * Created on Oct 10, 2019, 11:49:10 AM
 */
/**
 *
 * @author Kulbir Chand Katoch
 */
public class A2 extends javax.swing.JFrame {

    /** Creates new form A2 */
    public A2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        t2 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 36));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 12, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 24));
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("USER NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 3, 24));
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("CODE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 170, -1, -1));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 77, 251, 28));

        jButton1.setBackground(new java.awt.Color(51, 0, 51));
        jButton1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 3, 11));
        jButton1.setForeground(new java.awt.Color(102, 255, 102));
        jButton1.setText("LOGIN");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 228, 176, 33));

        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("*CREATE A ACCOUNT*");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 302, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 3, 11));
        jButton2.setForeground(new java.awt.Color(0, 255, 0));
        jButton2.setText("CREATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 300, -1, 19));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 170, 258, 30));

        jButton3.setText("check");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AYUSH1.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new A3().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
        Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost/AYUSH","root","root");
        Statement stmt=con.createStatement();
        String c;
       String A=t2.getText();
        String B=t1.getText();
        c="select * from a where password="+"'"+(B)+"'"+"and username="+"'"+(A)+"'";
        ResultSet rst=stmt.executeQuery(c);
        
        if(rst.next()==false)
        {
            JOptionPane.showMessageDialog(null,"invalid username or code");
        t2.setText("");
        t1.setText("");}
        else{
         
        rst.close();
        stmt.close();
        con.close();
        
         JOptionPane.showMessageDialog(null,"HY ASA(ayush space agency) MEMBER welcome");
         this.setVisible(false);
         new M1().setVisible(true);}
        }
        catch(Exception e )
        {
        JOptionPane.showMessageDialog(null,"error");
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"are you sure your codeis  {"+t2.getText()+"}  is it correct");
     
     
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new A2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField t1;
    private javax.swing.JPasswordField t2;
    // End of variables declaration//GEN-END:variables
}
