//<editor-fold defaultstate="collapsed" desc="comment">
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;

import java.sql.Statement;
import java.sql.ResultSet;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * M13.java
 *
 * Created on Oct 13, 2019, 1:47:25 PM
 */
/**
 *
 * @author Kulbir Chand Katoch
 */
public class M13 extends javax.swing.JFrame {

    /** Creates new form M13 */
    public M13() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        c1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        T2 = new javax.swing.JTextField();
        T3 = new javax.swing.JTextField();
        T4 = new javax.swing.JTextField();
        T5 = new javax.swing.JTextField();
        T6 = new javax.swing.JTextField();
        T7 = new javax.swing.JTextField();
        T8 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24));
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("TERMS AND CONDITIONS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 11, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("ALL THE INFORMATION GIVEN IS CORRECT AND ONCE INFORMATION GIVEN WILL NOT CHANGE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 78, -1, -1));

        c1.setBackground(new java.awt.Color(0, 0, 0));
        c1.setForeground(new java.awt.Color(255, 0, 51));
        c1.setText("I AGREE");
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18));
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("CONTINUE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 115, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18));
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 209, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18));
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("AGE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 259, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18));
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("NATIONALITY");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18));
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("CAST");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 361, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18));
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("SUBJECT(PHY/CHEM/MATH/ASTRONOMY)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 413, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 18));
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("DEGREE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 465, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 24));
        jButton2.setForeground(new java.awt.Color(255, 255, 51));
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 611, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 18));
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("PHONE NUB.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 518, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 18));
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("EMAIL");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 568, -1, -1));

        T1.setEditable(false);
        getContentPane().add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 213, 239, -1));

        T2.setEditable(false);
        getContentPane().add(T2, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 263, 239, -1));

        T3.setEditable(false);
        getContentPane().add(T3, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 314, 239, -1));

        T4.setEditable(false);
        getContentPane().add(T4, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 365, 239, -1));

        T5.setEditable(false);
        getContentPane().add(T5, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 417, 239, -1));

        T6.setEditable(false);
        getContentPane().add(T6, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 469, 239, -1));

        T7.setEditable(false);
        getContentPane().add(T7, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 522, 239, -1));

        T8.setEditable(false);
        getContentPane().add(T8, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 572, 239, -1));

        jButton3.setText(" BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ayush3.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(c1.isSelected())
        {
        T1.setEditable(true); T2.setEditable(true); T3.setEditable(true); T4.setEditable(true); T5.setEditable(true);
          T8.setEditable(true); T7.setEditable(true); T6.setEditable(true);
        }
        else
            JOptionPane.showMessageDialog(null,"AGREE TO CONTINUE");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
        Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ayush","root","root");
        Statement stmt=con.createStatement();
        String query="select * from b1;";
        ResultSet rs=stmt.executeQuery(query);
        String a=T1.getText();
        String c,d,e,f,g,h,b=T3.getText();
        c=T4.getText();d=T5.getText();f=T6.getText();h=T8.getText();
        String y,x=T7.getText();
        y=T2.getText();
        String strsql="INSERT INTO b1(name,age,nation,cast,subject,degree,mobile,email)"
                + " values('"+(a)+"','"+(y)+"','"+(b)+"','"+(c)+"','"+(d)+"','"+(f)+"','"+(x)+"','"+(h)+"');";
        int no_row=stmt.executeUpdate(strsql);
        JOptionPane.showMessageDialog(null,"IF YOU ARE SELECTED A EXAMINATION CODE WILL BE GIVEN AND CENTER WILL BE SEND");
        JOptionPane.showMessageDialog(null,"BEST OF LUCK");
        this.setVisible(false);
        new M1().setVisible(true);
        }
        catch(Exception e){
          JOptionPane.showMessageDialog(null,"whllly"); }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new M1().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new M13().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    private javax.swing.JTextField T6;
    private javax.swing.JTextField T7;
    private javax.swing.JTextField T8;
    private javax.swing.JCheckBox c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
