import javax.swing.JOptionPane;
import javax.swing.table.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
//<editor-fold defaultstate="collapsed" desc="comment">

/*
 * M15.java
 *
//<editor-fold defaultstate="collapsed" desc="comment">
 * Created on Oct 20, 2019, 8:23:03 PM
 */
/**
 *
 * @author Kulbir Chand Katoch
 */
public class M15 extends javax.swing.JFrame {

    /** Creates new form M15 */
    public M15() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36));
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("MISSION ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36));
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("ASTROID HUNTING");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 56, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18));
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("THIS IS ONLY THE MESSION WHICH IS BEEN FOLOWED AS ALL PUBLIC/VIEWERS CAN TAKE  PART IN THIS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 138, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("THIS HUNTING IS DONE USING VARIOUS ASTRONOMICAL SOFTWARES SUCH AS ASTROMATRICA STRADIUM ETC AND ALSO FIND PLANET WHICH IS NOT EASY TASK");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 178, 1191, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("AND EVEN THE ONE WHO FIND A TIPICAL ASTROID IS AWARDED FROM OUR AGENCY IT HEPLS OUR SCI. TO STUDY ABOUT EARTH AND OBJECT NEAR IT. ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 201, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("SO IF YOU FIND OR DISCOVER A NEW UNWANTED OBJ THEN MAIL US TO AYUSHSPACE@AGENCY.nic ALSO TOLL FREE NUB-332211.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 224, -1, 19));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 24));
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText(" TO SEE THE MEMBER DEPARTMENT OF ASTROID CLICK ON FIND");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 277, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 36));
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("FIND");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 312, -1, -1));

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "DEPARTMENT"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 376, 620, 95));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rajiv-bajaj-NPYqw5ZgGJs-unsplash.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      DefaultTableModel tm=(DefaultTableModel) jTable1.getModel();
        try
        {
        Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost/AYUSH","root","root");
        Statement stmt=con.createStatement();
        String query="select * from dept;";
        ResultSet rs=stmt.executeQuery(query);
        while(rs.next())
        {
        String a,b=rs.getString("name");
               a=rs.getString("department");
        Object[] obl={b,a};
        tm.addRow(obl);
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null, "eeee");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new M1().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new M15().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
